# -*- coding: utf-8 -*-

COURSES_CHOICES = (
       u'Licenciatura em Engenharia Física',
       u'Licenciatura em Antropologia',
       u'Licenciatura em Engenharia Informática',
       u'Licenciatura em Física',
       u'Licenciatura em Química',
       u'Licenciatura em Química Industrial',
       u'Licenciatura em Matemática',
       u'Licenciatura em Biologia',
       u'Licenciatura em Bioquímica',
       u'Licenciatura em Conservação e Restauro',
       u'Licenciatura em Geologia',
       u'Licenciatura em Design e Multimédia',
       u'Licenciatura em Engenharia e Gestão Industrial',
       u'Mestrado Integrado em Engenharia Civil',
       u'Mestrado Integrado em Engenharia do Ambiente',
       u'Mestrado Integrado em Engenharia Mecânica',
       u'Mestrado Integrado em Engenharia Química',
       u'Mestrado Integrado em Engenharia Electrotécnica e de Computadores',
       u'Mestrado Integrado em Arquitectura',
       u'Mestrado Integrado em Engenharia Biomédica',
       u'Mestrado em Antropologia Social e Cultural',
       u'Mestrado em Biologia',
       u'Mestrado em Bioquímica',
       u'Mestrado em Conservação e Restauro',
       u'Mestrado em Design e Multimédia',
       u'Mestrado em Engenharia de Materiais',
       u'Mestrado em Engenharia e Gestão Industrial',
       u'Mestrado em Instrumentação',
       u'Mestrado em Metrologia e Controlo de Qualidade',
       u'Mestrado em Engenharia Geográfica',
       u'Mestrado em Engenharia Geológica e de Minas',
       u'Mestrado em Engenharia Informática',
       u'Mestrado em Evolução e Biologia Humanas',
       u'Mestrado em Física',
       u'Mestrado em Geociências',
       u'Mestrado em Matemática',
       u'Mestrado em Química',
       u'Mestrado em Tecnologias de Informação Visual',
	)